version: '3.8'
name: parser

services:
  database:
    build:
      context: ./database
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  telegram_bot:
    build: ./telegram_bot
    depends_on:
      - database
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      POSTGRES_DB: vacancies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    command: python telegram_bot.py

volumes:
  postgres-data:

